include:
  - funnel/*
kind: ArchiveUploadSpec
name: funnel-Oskk

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: funnel
spec:
  deployment:
    checksum: {}
  environment:
    name: funnel
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://funnel-Oskk
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-03-14T11:58:22Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: funnel-edge-output
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
    - name: inference
      namespace: ""
  environment:
    name: funnel
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: __init__.main
    packageref:
      name: funnel
      namespace: ""
  requestsPerPod: 1
  resources: {}

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: funnel-fog-output
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
    - name: inference
      namespace: ""
  environment:
    name: funnel
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: __init__.main
    packageref:
      name: funnel
      namespace: ""
  requestsPerPod: 1
  resources: {}

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: funnel-cloud-output
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
    - name: inference
      namespace: ""
  environment:
    name: funnel
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: __init__.main
    packageref:
      name: funnel
      namespace: ""
  requestsPerPod: 1
  resources: {}

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: funnel-cloud-input
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
    - name: inference
      namespace: ""
  environment:
    name: funnel
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: __init__.main
    packageref:
      name: funnel
      namespace: ""
  requestsPerPod: 1
  resources: {}

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: funnel-fog-input
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
    - name: inference
      namespace: ""
  environment:
    name: funnel
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: __init__.main
    packageref:
      name: funnel
      namespace: ""
  requestsPerPod: 1
  resources: {}
