include:
  - src/*
kind: ArchiveUploadSpec
name: src-psFm

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: inference
spec:
  deployment:
    checksum: {}
  environment:
    name: tensorflow
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://src-psFm
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-03-09T11:39:03Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: edge
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
    - name: inference
      namespace: default
  environment:
    name: tensorflow
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: __init__.main
    packageref:
      name: inference
      namespace: ""
  requestsPerPod: 1
  resources: {}

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: fog
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
    - name: inference
      namespace: default
  environment:
    name: tensorflow
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: __init__.main
    packageref:
      name: inference
      namespace: ""
  requestsPerPod: 1
  resources: {}

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: cloud
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
    - name: inference
      namespace: default
  environment:
    name: tensorflow
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: __init__.main
    packageref:
      name: inference
      namespace: ""
  requestsPerPod: 1
  resources: {}
