apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-glue-flask-config
data:
  REDIS_HOSTNAME: redis-serverless.default.svc.cluster.local
  REDIS_PORT: "6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-glue-flask
  labels:
    name: redis-glue-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      name: redis-glue-flask
  template:
    metadata:
      labels:
        name: redis-glue-flask
    spec:
      containers:
        - name: redis-glue-flask
          image: 10.10.32.232:5000/redis-glue-flask:0.2.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: "/etc/redis-glue-config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: redis-glue-flask-config
---
# curl redis-glue-flask.default.svc.cluster.local:80 -X POST -H "Content-Type: application/json" -d '{"value": 10}'

apiVersion: v1
kind: Service
metadata:
  name: redis-glue-flask
  labels:
    name: redis-glue-flask
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    name: redis-glue-flask
