include:
- funnel/*
kind: ArchiveUploadSpec
name: funnel-YAF2

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: funnel
spec:
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://funnel-YAF2
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-03-30T09:11:36Z"
