# Sample Docker compose for local development
version: "3"
services:
  k6:
    environment:
      "SCRIPT_URL": "http://nginx:80"
      "K6_VUS": "2"
      "K6_DURATION": "3s"
      "K6_CSV_FILENAME": /d/out/results.csv
    image: grafana/k6:0.41.0
    command: run --out csv /d/script.js
    volumes:
      - "${PWD}/script.js:/d/script.js"
      - "${PWD}/out/:/d/out"
    depends_on:
      - nginx
  nginx:
    image: nginx
