apiVersion: v1
kind: Pod
metadata:
  name: k6-load-deployment-fission-default-1h-redis-glue-newdeploy-min1
spec:
  nodeName: node1
  restartPolicy: Never
  containers:
    - name: k6
      image: grafana/k6:0.41.0
      command: ["k6", "run", "-q", "--out", "csv", "/d/script.js"]
      env:
        - name: "SCRIPT_URL"
          value: "http://router.fission.svc.cluster.local:80/redis-glue-newdeploy-min1"
        - name: SCRIPT_DATASET
          value: "/d/payloads.json"
        - name: SCRIPT_RATE
          value: "1"
        - name: SCRIPT_DURATION
          value: "96h"
        - name: SCRIPT_TIMEUNIT
          value: "1h"
        - name: "K6_CSV_FILENAME"
          value: /d/out/results-fission-default-1h-redis-glue-newdeploy-min1.csv
        - name: K6_NO_VU_CONNECTION_REUSE
          value: "true"
        - name: K6_CSV_SAVE_INTERVAL
          value: "5m"
      volumeMounts:
        - mountPath: /d/out
          name: k6-csv
        - mountPath: /d/script.js
          name: k6-script
        - mountPath: /d/payloads.json
          name: k6-payloads
  volumes:
    - name: k6-csv
      hostPath:
        path: /lambda/k6/out
        type: DirectoryOrCreate
    - name: k6-script
      hostPath:
        path: /lambda/k6/k6-constant-arrival-rate.js
        type: File
    - name: k6-payloads
      hostPath:
        path: /lambda/k6/payloads/precio-energias-de-balance.json
        type: File
