# Config maps for Fission functions
# $ kubectl create -f config_map.yml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: inference
data:
  cloud: |-
    {
      "exit": {
        "url": "http://router.fission/funnel-cloud-output"
      },
      "model": "cloud.h5"
    }
  fog: |-
    {
      "exit": {
        "url": "http://router.fission/funnel-fog-output"
      },
      "next": {
        "url": "http://router.fission/funnel-cloud-input",
        "confidence": 0.50
      },
      "model": "fog.h5"
    }
  edge: |-
    {
      "exit": {
        "url": "http://router.fission/funnel-edge-output"
      },
      "next": {
        "url": "http://router.fission/funnel-fog-input",
        "confidence": 0.65
      },
      "model": "edge.h5"
    }
  funnel-edge-output: |-
    {
      "topic": "fission.inference.edge-output",
      "producer":{
        "bootstrap_servers": [
          "kafka-0.kafka-headless.kafka:9092",
          "kafka-1.kafka-headless.kafka:9092",
          "kafka-2.kafka-headless.kafka:9092",
          "kafka-3.kafka-headless.kafka:9092",
          "kafka-4.kafka-headless.kafka:9092",
          "kafka-5.kafka-headless.kafka:9092"
        ]
      }
    }
  funnel-fog-output: |-
    {
      "topic": "fission.inference.fog-output",
      "producer":{
        "bootstrap_servers": [
          "kafka-0.kafka-headless.kafka:9092",
          "kafka-1.kafka-headless.kafka:9092",
          "kafka-2.kafka-headless.kafka:9092",
          "kafka-3.kafka-headless.kafka:9092",
          "kafka-4.kafka-headless.kafka:9092",
          "kafka-5.kafka-headless.kafka:9092"
        ]
      }
    }
  funnel-cloud-output: |-
    {
      "topic": "fission.inference.cloud-output",
      "producer":{
        "bootstrap_servers": [
          "kafka-0.kafka-headless.kafka:9092",
          "kafka-1.kafka-headless.kafka:9092",
          "kafka-2.kafka-headless.kafka:9092",
          "kafka-3.kafka-headless.kafka:9092",
          "kafka-4.kafka-headless.kafka:9092",
          "kafka-5.kafka-headless.kafka:9092"
        ]
      }
    }
  funnel-fog-input: |-
    {
      "topic": "fission.inference.fog-input",
      "producer":{
        "bootstrap_servers": [
          "kafka-0.kafka-headless.kafka:9092",
          "kafka-1.kafka-headless.kafka:9092",
          "kafka-2.kafka-headless.kafka:9092",
          "kafka-3.kafka-headless.kafka:9092",
          "kafka-4.kafka-headless.kafka:9092",
          "kafka-5.kafka-headless.kafka:9092"
        ]
      }
    }
  funnel-cloud-input: |-
    {
      "topic": "fission.inference.cloud-input",
      "producer":{
        "bootstrap_servers": [
          "kafka-0.kafka-headless.kafka:9092",
          "kafka-1.kafka-headless.kafka:9092",
          "kafka-2.kafka-headless.kafka:9092",
          "kafka-3.kafka-headless.kafka:9092",
          "kafka-4.kafka-headless.kafka:9092",
          "kafka-5.kafka-headless.kafka:9092"
        ]
      }
    }
