edge_input = keras.Input(shape=(28,28,1), name='input_img')
x = tf.keras.layers.Flatten(name='flatten')(edge_input)
output_to_fog = tf.keras.layers.Dense(32, activation=tf.nn.relu, name='output_to_fog')(x)
edge_output = tf.keras.layers.Dense(10, activation=tf.nn.softmax, name='edge_output')(output_to_fog)
edge_model = keras.Model(inputs=[edge_input], outputs=[output_to_fog, edge_output], name='edge_model')