apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: funnel-cloud-input
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: inference
    namespace: ""
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: __init__.main
    packageref:
      name: funnel
      namespace: ""
  requestsPerPod: 1
  resources: {}
