apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: funnel-cloud-input
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: funnel-cloud-input
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /funnel-cloud-input
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /funnel-cloud-input
