apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: model-inference-7
  name: model-inference-7
  namespace: kafkaml
spec:
  replicas: 1
  selector:
    app: inference7
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: inference7
    spec:
      containers:
        - env:
            - name: INPUT_BOOTSTRAP_SERVERS
              value: kafka.kafka:9092
            - name: OUTPUT_BOOTSTRAP_SERVERS
              value: kafka.kafka:9092
            - name: UPPER_BOOTSTRAP_SERVERS
              value: 192.168.43.7:32001
            - name: MODEL_URL
              value: http://192.168.43.7:8080/fog.h5
            - name: INPUT_FORMAT
              value: RAW
            - name: INPUT_CONFIG
              value:
                '{"data_type": "uint8", "label_type": "uint8", "data_reshape":
                "28 28", "label_reshape": "1"}'
            - name: INPUT_TOPIC
              value: kafkaml.inference2.input-fog
            - name: OUTPUT_TOPIC
              value: kafkaml.inference2.output-fog
            - name: OUTPUT_UPPER
              value: kafkaml.inference2.input-cloud
            - name: GROUP_ID
              value: inf2
            - name: LIMIT
              value: "0.5000000000"
          image: ertis/kafka-ml-tensorflow_model_inference:master
          imagePullPolicy: Always
          name: inference
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
