apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: funnel-edge-output
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: funnel-edge-output
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /funnel-edge-output
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /funnel-edge-output
