apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: d60f7fea-5ad7-4579-9542-9e8347b4fda0
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: redis-glue-newdeploy-min1
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /redis-glue-newdeploy-min1
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /redis-glue-newdeploy-min1
