apiVersion: v1
kind: Pod
metadata:
  name: k6-load-deployment-fission-default-1h-redis-glue
spec:
  nodeName: node1
  restartPolicy: Never
  containers:
    - name: k6
      image: grafana/k6:0.41.0
      command: ["k6", "run", "--out", "csv", "/d/script.js"]
      env:
        - name: "SCRIPT_URL"
          value: "http://router.fission.svc.cluster.local:80/redis-glue"
        - name: SCRIPT_DATASET
          value: "/d/payloads.json"
        - name: "K6_VUS"
          value: "1"
        - name: SCRIPT_SLEEP_FOR
          value: "3600" # 60m * 60s/m = 3600s
        - name: "K6_CSV_FILENAME"
          value: /d/out/results-fission-default-1h-redis-glue.csv
      volumeMounts:
        - mountPath: /d/out
          name: k6-csv
        - mountPath: /d/script.js
          name: k6-script
        - mountPath: /d/payloads.json
          name: k6-payloads
  volumes:
    - name: k6-csv
      hostPath:
        path: /lambda/k6/out
        type: DirectoryOrCreate
    - name: k6-script
      hostPath:
        path: /lambda/k6/script-sleep.js
        type: File
    - name: k6-payloads
      hostPath:
        path: /lambda/k6/payloads/precio-energias-de-balance-small.json
        type: File
