include:
- src/*
kind: ArchiveUploadSpec
name: src-vq2M

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: redis-glue-d8f411d6-5210-47dd-ac7b-54c56623395b
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://src-vq2M
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-01-03T14:43:56Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: redis-glue
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: redis-glue
    namespace: default
  environment:
    name: python
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.main
    packageref:
      name: redis-glue-d8f411d6-5210-47dd-ac7b-54c56623395b
      namespace: default
  requestsPerPod: 1
  resources: {}
