apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 49282259-03b5-40b8-ab11-5a1f164d74b2
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: redis-glue
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /redis-glue
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /redis-glue
