apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: 1114f6ec-e827-4f30-a8ed-a148fe17fbfc
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: redis-glue-newdeploy
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /redis-glue-newdeploy
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /redis-glue-newdeploy
