# $ kubectl get configmaps prometheus-config -n openfaas -o yaml > patch.yml
# Modify rule: sum(rate(gateway_function_invocation_total{code=~"2.."}[10s])) BY (function_name) > 5
# $ kubectl apply -f patch.yml
# $ kubectl delete pod -l app=prometheus -n openfaas
apiVersion: v1
data:
  alert.rules.yml: |
    groups:
      - name: openfaas
        rules:
        - alert: APIHighInvocationRate
          expr: sum(rate(gateway_function_invocation_total{code=~"2.."}[30s])) BY (function_name) > 3.5
          for: 3s
          labels:
            service: gateway
            severity: major
          annotations:
            description: High invocation total on "{{$labels.function_name}}"
            summary: High invocation total on "{{$labels.function_name}}"
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
      external_labels:
          monitor: 'faas-monitor'

    rule_files:
        - 'alert.rules.yml'

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - alertmanager:9093

    scrape_configs:
      - job_name: 'prometheus'
        scrape_interval: 10s
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'openfaas-pods'
        scrape_interval: 5s
        honor_labels: false
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - openfaas
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: openfaas
    meta.helm.sh/release-namespace: openfaas
  labels:
    app: openfaas
    app.kubernetes.io/managed-by: Helm
    chart: openfaas-11.1.13
    component: prometheus-config
    heritage: Helm
    release: openfaas
  name: prometheus-config
  namespace: openfaas
