include:
- funnel/*
kind: ArchiveUploadSpec
name: funnel-AMQK

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: funnel-cloud-output-4a9cf447-c499-4195-9049-32ab8f8f408e
spec:
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://funnel-AMQK
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-03-30T09:46:30Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: funnel-cloud-output
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: inference
    namespace: ""
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: __init__.main
    packageref:
      name: funnel-cloud-output-4a9cf447-c499-4195-9049-32ab8f8f408e
      namespace: ""
  requestsPerPod: 1
  resources: {}
