include:
- inference/*
kind: ArchiveUploadSpec
name: inference-emjY

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: cloud-a4d6c2cc-0d39-4580-a205-b095121172aa
spec:
  deployment:
    checksum: {}
  environment:
    name: tensorflow
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://inference-emjY
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-03-30T09:46:30Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: cloud
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: inference
    namespace: ""
  environment:
    name: tensorflow
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: __init__.main
    packageref:
      name: cloud-a4d6c2cc-0d39-4580-a205-b095121172aa
      namespace: ""
  requestsPerPod: 1
  resources: {}
