include:
- inference/*
kind: ArchiveUploadSpec
name: inference-ZHDo

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: fog-52a5e9d4-2020-45e6-8cf7-b74ef129d0b3
spec:
  deployment:
    checksum: {}
  environment:
    name: tensorflow
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://inference-ZHDo
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-03-28T09:29:25Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: fog
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 20
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: inference
    namespace: ""
  environment:
    name: tensorflow
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: __init__.main
    packageref:
      name: fog-52a5e9d4-2020-45e6-8cf7-b74ef129d0b3
      namespace: ""
  requestsPerPod: 1
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: "1"
      memory: 1Gi
