include:
- funnel/*
kind: ArchiveUploadSpec
name: funnel-cjV5

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: funnel
spec:
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://funnel-cjV5
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-03-28T09:29:26Z"
