include:
- inference/*
kind: ArchiveUploadSpec
name: inference-zdQ8

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: cloud-18c38975-2d27-477e-8f6f-98ee4eed252e
spec:
  deployment:
    checksum: {}
  environment:
    name: tensorflow
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://inference-zdQ8
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-03-27T10:53:58Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: cloud
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 20
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: inference
    namespace: ""
  environment:
    name: tensorflow
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: __init__.main
    packageref:
      name: cloud-18c38975-2d27-477e-8f6f-98ee4eed252e
      namespace: ""
  requestsPerPod: 1
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: "1"
      memory: 1Gi
