apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: cloud
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: cloud
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /cloud
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /cloud
